# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ldap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ldap.proto',
  package='dap',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nldap.proto\x12\x03\x64\x61p\"\x85\x01\n\x04ldap\x12\x1c\n\x04type\x18\x01 \x02(\x0e\x32\x0e.dap.ldap.Type\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07request\x18\x03 \x01(\t\x12\x10\n\x08response\x18\x04 \x01(\t\"0\n\x04Type\x12\x08\n\x04\x42IND\x10\x00\x12\t\n\x05QUERY\x10\x01\x12\x07\n\x03\x41\x44\x44\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03')
)



_LDAP_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='dap.ldap.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BIND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=105,
  serialized_end=153,
)
_sym_db.RegisterEnumDescriptor(_LDAP_TYPE)


_LDAP = _descriptor.Descriptor(
  name='ldap',
  full_name='dap.ldap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='dap.ldap.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='dap.ldap.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='dap.ldap.request', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='dap.ldap.response', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LDAP_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=153,
)

_LDAP.fields_by_name['type'].enum_type = _LDAP_TYPE
_LDAP_TYPE.containing_type = _LDAP
DESCRIPTOR.message_types_by_name['ldap'] = _LDAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ldap = _reflection.GeneratedProtocolMessageType('ldap', (_message.Message,), dict(
  DESCRIPTOR = _LDAP,
  __module__ = 'ldap_pb2'
  # @@protoc_insertion_point(class_scope:dap.ldap)
  ))
_sym_db.RegisterMessage(ldap)


# @@protoc_insertion_point(module_scope)
